service: Theraphy-nodejs-awsLambda

provider:
    name: aws
    runtime: nodejs12.x
    memorySize: 128
    timeout: 3
    stage: production
    region: ap-northeast-2

functions:
    api:
        handler: lambda.handler
        events:
            - http: ANY {proxy+}
            - http: ANY /
            - http: POST /

custom:
    assets:
        targets:
            - bucket: theraphy-nodejs-awslambd-serverlessdeploymentbuck-na2ptslfmsyq,
